version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - '3305:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycard
    volumes:
      - "./src/helpers/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/helpers/seed.sql:/docker-entrypoint-initdb.d/2.sql"
  keycard-api:
    build: .
    ports:
      - "3007:3007"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  mysql:
    driver: local
