version: '3.8'
services:
  keycard:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    entrypoint: 
      - sh
      - -c
      - >
        sed "s/%DEV_ETH_ADDRESS%/$$DEV_ETH_ADDRESS/g" /fixture_template/fixtures.sql > /docker-entrypoint-initdb.d/x_fixtures.sql &&
        exec docker-entrypoint.sh mysqld    
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      DEV_ETH_ADDRESS: ${DEV_ETH_ADDRESS}
    volumes:
      - mysql:/var/lib/mysql
      - ./src/helpers/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/helpers/fixtures.sql:/fixture_template/fixtures.sql

volumes:
  mysql:
    driver: local
