version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=default_password
      - MYSQL_DATABASE=keycard
    volumes:
      - mysql:/var/lib/mysql
  keycard-api:
    build: .
    ports:
      - "3007:3007"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  mysql:
    driver: local
